=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML I/4/4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="contrato">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="clausula" minOccurs="0" maxOccurs="unbounded" >
          <xs:complexType>
            <xs:sequence>
              <xs:element name="epigrafe" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="desarrollo" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="epilogo" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML I/4/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<contrato xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/1DAM01/Documents/SergioMartinez/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS%20XML%20I/4.xsd">

<clausula>
<epigrafe>
<desarrollo></desarrollo>
</epigrafe>
<epigrafe>
<desarrollo></desarrollo>
<desarrollo></desarrollo>
</epigrafe>
<epilogo></epilogo>
</clausula>

<clausula>
<epigrafe>
<desarrollo></desarrollo>
<desarrollo></desarrollo>
<desarrollo></desarrollo>
</epigrafe>
<epilogo></epilogo>
</clausula>

</contrato>
