=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML III/3/temporada.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="temporada">
		<xs:complexType>
			<xs:sequence>
			
				<xs:element name="jornada" type="Xjornada" minOccurs="5" maxOccurs="5"/>
				
			</xs:sequence>
			
			<xs:attribute name="año" type="xs:gYear" use="required"/>
			
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="Xjornada">
		<xs:sequence>
		
			<xs:element name="partido" type="Xpartido" minOccurs="3" maxOccurs="3"/>
		
		</xs:sequence>
		
		<xs:attribute name="numero" type="xs:NMTOKEN"/>
		
	</xs:complexType>
	
	<xs:complexType name="Xpartido">
		<xs:sequence>
		
			<xs:element name="fecha" type="xs:date"/>
			<xs:element name="estadio" type="Xestadio"/>
			<xs:element name="local" type="Xequipo"/>
			<xs:element name="visitante" type="Xequipo"/>
			
			<xs:choice>
			
				<xs:element name="resultado" type="Xresultado"/>
				<xs:element name="aplazado"/>
		
			</xs:choice>
			
		</xs:sequence>
		
		<xs:attribute name="numero" type="xs:NMTOKEN"/>
		
	</xs:complexType>
	
	<xs:complexType name="Xestadio">
		<xs:simpleContent>
	
			<xs:extension base="xs:string">
			
				<xs:attribute name="espectadores" type="Xespectadores" default="0"/>
			
			</xs:extension>
		
		</xs:simpleContent> 
	</xs:complexType>
	
	<xs:simpleType name="Xespectadores">
	  
		<xs:restriction base="xs:integer">
			
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="80000"/>
			
		</xs:restriction>  
	  
	</xs:simpleType>
	
	<xs:simpleType name="Xequipo">
	
		<xs:restriction base="xs:string">
		
			<xs:enumeration value="Italia"/>
			<xs:enumeration value="Escocia"/>
			<xs:enumeration value="Inglaterra"/>
			<xs:enumeration value="Irlanda"/>
			<xs:enumeration value="Gales"/>
			<xs:enumeration value="Francia"/>
			
		</xs:restriction>
		
	</xs:simpleType>
	
	<xs:complexType name="Xresultado">
		
		<xs:attribute name="local" type="xs:integer" use="required"/>
		<xs:attribute name="visitante" type="xs:integer" use="required"/>
		
	</xs:complexType>

</xs:schema>

=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML III/3/temporada.xml
<?xml version="1.0" encoding="UTF-8"?>
<temporada año="2000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="temporada.xsd">
	<jornada numero="1">
		<partido numero="1">
			<fecha>2000-02-05</fecha>
			<estadio espectadores="24000">Stadio Flaminio</estadio>
			<local>Italia</local>
			<visitante>Escocia</visitante>
			<resultado local="32" visitante="20"/>
		</partido>
		<partido numero="2">
			<fecha>2000-02-05</fecha>
			<estadio>Twickenham</estadio>
			<local>Inglaterra</local>
			<visitante>Irlanda</visitante>
			<aplazado/>
		</partido>
		<partido numero="3">
			<fecha>2000-02-05</fecha>
			<estadio espectadores="72500">Millennium Stadium</estadio>
			<local>Gales</local>
			<visitante>Francia</visitante>
			<resultado local="3" visitante="36"/>
		</partido>
	</jornada>
	<jornada numero="2">
		<partido numero="1">
			<fecha>2000-02-19</fecha>
			<estadio espectadores="78000">Stade de France</estadio>
			<local>Francia</local>
			<visitante>Inglaterra</visitante>
			<resultado local="9" visitante="15"/>
		</partido>
		<partido numero="2">
			<fecha>2000-02-19</fecha>
			<estadio espectadores="72500">Millennium Stadium</estadio>
			<local>Gales</local>
			<visitante>Italia</visitante>
			<resultado local="47" visitante="16"/>
		</partido>
		<partido numero="3">
			<fecha>2000-02-19</fecha>
			<estadio espectadores="40000">Lansdowne Road</estadio>
			<local>Irlanda</local>
			<visitante>Escocia</visitante>
			<resultado local="44" visitante="22"/>
		</partido>
	</jornada>
	<jornada numero="3">
		<partido numero="1">
			<fecha>2000-03-04</fecha>
			<estadio espectadores="67500">Murrayfield</estadio>
			<local>Escocia</local>
			<visitante>Francia</visitante>
			<resultado local="16" visitante="28"/>
		</partido>
		<partido numero="2">
			<fecha>2000-03-04</fecha>
			<estadio espectadores="73500">Twickenham</estadio>
			<local>Inglaterra</local>
			<visitante>Gales</visitante>
			<resultado local="17" visitante="6"/>
		</partido>
		<partido numero="3">
			<fecha>2000-03-04</fecha>
			<estadio espectadores="40000">Lansdowne Road</estadio>
			<local>Irlanda</local>
			<visitante>Italia</visitante>
			<resultado local="17" visitante="6"/>
		</partido>
	</jornada>
	<jornada numero="4">
		<partido numero="1">
			<fecha>2000-03-18</fecha>
			<estadio espectadores="30000">Stadio Flaminio</estadio>
			<local>Italia</local>
			<visitante>Inglaterra</visitante>
			<resultado local="12" visitante="59"/>
		</partido>
		<partido numero="2">
			<fecha>2000-02-19</fecha>
			<estadio espectadores="72500">Millennium Stadium</estadio>
			<local>Gales</local>
			<visitante>Escocia</visitante>
			<resultado local="26" visitante="18"/>
		</partido>
		<partido numero="3">
			<fecha>2000-02-19</fecha>
			<estadio espectadores="65000">Stade de France</estadio>
			<local>Francia</local>
			<visitante>Irlanda</visitante>
			<resultado local="25" visitante="27"/>
		</partido>
	</jornada>
	<jornada numero="5">
		<partido numero="1">
			<fecha>2000-04-01</fecha>
			<estadio espectadores="77000">Stade de France</estadio>
			<local>Francia</local>
			<visitante>Italia</visitante>
			<resultado local="42" visitante="31"/>
		</partido>
		<partido numero="2">
			<fecha>2000-02-19</fecha>
			<estadio espectadores="40000">Lansdowne Road</estadio>
			<local>Irlanda</local>
			<visitante>Gales</visitante>
			<resultado local="19" visitante="23"/>
		</partido>
		<partido numero="3">
			<fecha>2000-02-19</fecha>
			<estadio espectadores="67500">Murrayfield</estadio>
			<local>Escocia</local>
			<visitante>Inglaterra</visitante>
			<resultado local="19" visitante="13"/>
		</partido>
	</jornada>
</temporada>
