=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML II/6/tabla_periodica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="tabla_periodica">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="atomo" type="Xatomo" maxOccurs="unbounded"/>

			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Xatomo">
		<xs:sequence>

			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="simbolo" type="Xsimbolo"/>
			<xs:element name="numero_atomico" type="xs:integer"/>
			<xs:element name="peso_atomico" type="xs:float"/>
			<xs:element name="punto_ebullicion" type="Xpunto_ebullicion"/>
			<xs:element name="densidad" type="Xdensidad"/>

		</xs:sequence>

		<xs:attribute name="estado" type="Xestado"/>

	</xs:complexType>

	<xs:simpleType name="Xestado">
		<xs:restriction base="xs:string">

			<xs:enumeration value="solido"/>
			<xs:enumeration value="liquido"/>
			<xs:enumeration value="gaseoso"/>

		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Xsimbolo">
		<xs:restriction base="xs:string">

			<xs:pattern value="[A-Z][a-z]?[a-z]?"/>

		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="Xpunto_ebullicion">
		<xs:simpleContent>

			<xs:extension base="xs:float">

				<xs:attribute name="unidades" type="Xunidades_temperatura" default="centigrados"/>

			</xs:extension>

		</xs:simpleContent>
	</xs:complexType>
	
	<xs:simpleType name="Xunidades_temperatura">
		<xs:restriction base="xs:string">
		
			<xs:enumeration value="centigrados"/>
			<xs:enumeration value="kelvin"/>
		
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="Xdensidad">
		<xs:simpleContent>
      
			<xs:extension base="xs:float">
      
				<xs:attribute name="unidades" type="xs:string"/>
      
			</xs:extension>
      
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML II/6/tabla_periodica.xml
<?xml version="1.0" encoding="UTF-8"?>
<tabla_periodica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tabla_periodica.xsd">
	<atomo estado="gaseoso">
		<nombre>Hidrogeno</nombre>
		<simbolo>H</simbolo>
		<numero_atomico>1</numero_atomico>
		<peso_atomico>1.00794</peso_atomico>
		<punto_ebullicion unidades="kelvin">20.28</punto_ebullicion>
		<densidad unidades="gramos/centimetros cubicos">0.0899</densidad>
	</atomo>
	<atomo estado="gaseoso">
		<nombre>Helio</nombre>
		<simbolo>He</simbolo>
		<numero_atomico>2</numero_atomico>
		<peso_atomico>4.0026</peso_atomico>
		<punto_ebullicion unidades="kelvin">4.216</punto_ebullicion>
		<densidad unidades="gramos/centimetros cubicos">0.1785</densidad>
	</atomo>
</tabla_periodica>
