=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML II/1/persona2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="persona2">
    <xs:complexType>
      <xs:sequence>
	  
        <xs:element name="Nombre" type="xs:string"/>
        <xs:element name="Profesion" type="xs:string"/>
        <xs:element name="Direccion" type="XDireccion"/>
        <xs:element name="Telefono" type="XTelefono"/>
		
      </xs:sequence>
    </xs:complexType>
  </xs:element>

    <xs:complexType name="XDireccion">
      <xs:sequence>
	  
        <xs:element name="Calle" type="xs:string"/>
        <xs:element name="Numero" type="XNumero"/>
        <xs:element name="Provincia" type="xs:string"/>
		
      </xs:sequence>
    </xs:complexType>
	
	<xs:simpleType name="XTelefono">
		
		<xs:restriction base="xs:string">
		
			<xs:pattern value="\d{3}\-\d{2}\-\d{2}\-\d{2}"/>
		
		</xs:restriction>
		
	</xs:simpleType>
	
	<xs:simpleType name="XNumero">
		
		<xs:restriction base="xs:string">
		
			<xs:pattern value="\d{0,3}"/>
			<xs:maxLength value="3"/>
		
		</xs:restriction>
		
	</xs:simpleType>
    
</xs:schema>

=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML II/1/persona2.xml
<persona2 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "persona2.xsd">
  <Nombre>Luis Quintana</Nombre>
  <Profesion>Profesor</Profesion>
  <Direccion>
    <Calle>Avenida de los Poblados</Calle>
    <Numero>6</Numero>
    <Provincia>Zaragoza</Provincia>
  </Direccion>
  <Telefono>968-21-43-56</Telefono>
</persona2>
