<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email [
<!ELEMENT email (para,cc?,cco?,asunto,cuerpo)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!ELEMENT cco (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>]>
  
<email>
  <para>Sergio</para>
  <cc></cc>
  <cco></cco>
  <asunto>Hola</asunto>
  <cuerpo>Hola</cuerpo>
</email>
