=== sergiomm116/DAMGit/LENGUAJE/EXAMEN/XML.DTD/EJERCICIO 2/universidad.dtd
<!ELEMENT universidad (alumnos, asignaturas)>

<!ELEMENT alumnos (alumno+)>
<!ELEMENT asignaturas (asignatura+)>
<!ELEMENT asignatura (titulo, carrera, creditos?, curso?)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT carrera (#PCDATA)>
<!ELEMENT creditos (#PCDATA)>
<!ELEMENT curso (#PCDATA)>

<!ATTLIST asignatura codigo ID #REQUIRED>

<!ELEMENT alumno (nombre, (apellido | (apellido | apellido2)), (pasaporte | nif), fechanacimiento, matriculado)>
<!ELEMENT fechanacimiento (dia, mes, anio)>

<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT pasaporte (#PCDATA)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT matriculado (#EMPTY)>

<!ATTLIST nif letra ID #REQUIRED>

<!ATTLIST matriculado materia IDREDS #REQUIRED>
<!ATTLIST matriculado nota (NP | IN | SF | BI | NT | SB | MH | NP) "NP">

=== sergiomm116/DAMGit/LENGUAJE/EXAMEN/XML.DTD/EJERCICIO 2/universidad.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE universidad SYSTEM "universidad.dtd">
<universidad>
	<alumnos>
		<alumno>
			<nombre>pepe</nombre>
			<apellido>pinillos</apellido>
			<pasaporte>434235</pasaporte>
			<fechanacimiento>
				<dia>32</dia>
				<mes>43</mes>
				<anio>5256</anio>
			</fechanacimiento>
			<matriculado materia="F89" nota="NT"/>
		</alumno>
	</alumnos>
	<asignaturas>
		<asignatura codigo="F89">
			<titulo>Lenguajes Marcas</titulo>
			<carrera>ITIS</carrera>
			<creditos>4,5</creditos>
			<curso>OP</curso>
		</asignatura>
		<asignatura codigo="A990">
			<titulo>Bases de datos</titulo>
			<carrera>ITGEST</carrera>
		</asignatura>
	</asignaturas>
</universidad>
