=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML III/2/vehicles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="vehicles">
		<xs:complexType>
			<xs:sequence>
			
				<xs:element name="vehicle" type="Xvehicle"/>
				
			</xs:sequence>
			
			<xs:attribute name="id" use="required"/>
			
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="Xvehicle">
		<xs:sequence>
		
			<xs:element name="nickname" type="xs:string"/>
			<xs:element name="model" type="xs:string"/>
			<xs:element name="construction" type="Xconstruction"/>
			<xs:element name="mods" type="Xmods"/>
		
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Xconstruction">
		<xs:sequence>
		
			<xs:element name="start" type="Xfecha"/>
			<xs:element name="end" type="Xfecha"/>
		
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Xfecha">
		<xs:sequence>
		
			<xs:element name="dom" type="xs:string"/>
			<xs:element name="month" type="xs:string"/>
			<xs:element name="year" type="xs:string"/>
			
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Xmods">
		<xs:sequence>
		
			<xs:element name="mod" type="xs:string" maxOccurs="unbounded"/>
			
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML III/2/vehicles.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehicles id="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vehicles.xsd">
	<vehicle>
		<nickname>Count Zero</nickname>
		<model>Series I, 80"</model>
		<construction>
			<start>
				<dom>21</dom>
				<month>July</month>
				<year>1949</year>
			</start>
			<end>
				<dom>9</dom>
				<month>August</month>
				<year>1949</year>
			</end>
		</construction>
		<mods>
			<mod>Change Engine</mod>
			<mod>Change pedals</mod>
			<mod>Change gearbox</mod>
			<mod>Fit Rollcage</mod>
		</mods>
	</vehicle>
</vehicles>
