=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML II/7/prestamo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="prestamo">
		<xs:complexType>
			<xs:sequence>
				
				<xs:element name="bibliotecario" type="Xbibliotecario"/>
				<xs:element name="fecha" type="Xfecha"/>
				<xs:element name="lector" type="Xlector"/>
				<xs:element name="ejemplar" type="Xejemplar" maxOccurs="3"/>

			</xs:sequence>
			
			<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
			
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Xbibliotecario">
			<xs:sequence>
				
				<xs:element name="nombre" type="xs:string"/>
				<xs:element name="apellidos" type="xs:string"/>
				
			</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Xfecha">
		<xs:sequence>
				
			<xs:element name="prestamo" type="xs:date"/>
			<xs:element name="devolucion" type="xs:date"/>
				
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Xlector">
		<xs:sequence>
				
			<xs:element name="id_lector" type="xs:NMTOKEN"/>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="apellidos" type="xs:string"/>
			<xs:element name="telefono" type="xs:string"/>
			<xs:element name="direccion" type="Xdireccion"/>
				
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Xdireccion">
		<xs:sequence>
				
			<xs:element name="tipo_calle" type="Xtipo_calle"/>
			<xs:element name="nombre_calle" type="xs:string"/>
			<xs:element name="numero" type="xs:string"/>
			<xs:element name="piso" type="xs:string"/>
			<xs:element name="letra" type="xs:string"/>
			<xs:element name="cp" type="xs:string"/>
			<xs:element name="localidad" type="xs:string"/>
			<xs:element name="provincia" type="xs:string"/>
				
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="Xtipo_calle">
		<xs:restriction base="xs:string">

			<xs:enumeration value="Calle"/>
			<xs:enumeration value="Avenida"/>
			<xs:enumeration value="Plaza"/>

		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="Xejemplar">
		<xs:sequence>
				
			<xs:element name="num_registro" type="xs:NMTOKEN"/>
			<xs:element name="titulo" type="xs:string"/>
			<xs:element name="autor" type="xs:string" maxOccurs="unbounded"/>

		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== sergiomm116/DAMGit/LENGUAJE/EJERCICIOS/XML.ESQUEMAS/ENTREGAS/ESQUEMAS XML II/7/prestamo.xml
<?xml version="1.0" encoding="UTF-8"?>
<prestamo id="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="prestamo.xsd">
	<bibliotecario>
		<nombre>Arturo</nombre>
		<apellidos>Lopez Garcia</apellidos>
	</bibliotecario>
	<fecha>
		<prestamo>2020-04-26</prestamo>
		<devolucion>2020-04-28</devolucion>
	</fecha>
	<lector>
		<id_lector>1</id_lector>
		<nombre>Sergio</nombre>
		<apellidos>Martinez Martinez</apellidos>
		<telefono>666666666</telefono>
		<direccion>
			<tipo_calle>Calle</tipo_calle>
			<nombre_calle>Falsa</nombre_calle>
			<numero>123</numero>
			<piso>4</piso>
			<letra>A</letra>
			<cp>16000</cp>
			<localidad>Cuenca</localidad>
			<provincia>Cuenca</provincia>
		</direccion>
	</lector>
	<ejemplar>
		<num_registro>1547</num_registro>
		<titulo>Don Quijote de la Mancha</titulo>
		<autor>Miguel de Cervantes</autor>
		<autor>El manco de Lepanto</autor>
	</ejemplar>
	<ejemplar>
		<num_registro>3462</num_registro>
		<titulo>El Codigo Da Vinci</titulo>
		<autor>Dan Brown</autor>
	</ejemplar>
	<ejemplar>
		<num_registro>45634</num_registro>
		<titulo>Gomorra</titulo>
		<autor>Roberto Saviano</autor>
	</ejemplar>
</prestamo>
